"""Initial migration

Revision ID: 2aacf8c53ae4
Revises: 
Create Date: 2025-11-15 00:41:47.056020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aacf8c53ae4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomenclature', sa.String(length=500), nullable=False),
    sa.Column('balance_date', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('warehouse', sa.String(length=200), nullable=False),
    sa.Column('batch_number', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_balances_balance_date'), 'batch_balances', ['balance_date'], unique=False)
    op.create_index(op.f('ix_batch_balances_batch_number'), 'batch_balances', ['batch_number'], unique=False)
    op.create_index(op.f('ix_batch_balances_nomenclature'), 'batch_balances', ['nomenclature'], unique=False)
    op.create_table('batch_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomenclature', sa.String(length=500), nullable=False),
    sa.Column('movement_date', sa.DateTime(), nullable=False),
    sa.Column('movement_type', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('warehouse', sa.String(length=200), nullable=False),
    sa.Column('batch_number', sa.String(length=200), nullable=True),
    sa.Column('document_name', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_movements_batch_number'), 'batch_movements', ['batch_number'], unique=False)
    op.create_index(op.f('ix_batch_movements_movement_date'), 'batch_movements', ['movement_date'], unique=False)
    op.create_index(op.f('ix_batch_movements_nomenclature'), 'batch_movements', ['nomenclature'], unique=False)
    op.create_table('shrinkage_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomenclature', sa.String(length=500), nullable=False),
    sa.Column('calculated_shrinkage', sa.Float(), nullable=False),
    sa.Column('actual_balance', sa.Float(), nullable=False),
    sa.Column('deviation', sa.Float(), nullable=False),
    sa.Column('calculation_date', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shrinkage_calculations_nomenclature'), 'shrinkage_calculations', ['nomenclature'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shrinkage_calculations_nomenclature'), table_name='shrinkage_calculations')
    op.drop_table('shrinkage_calculations')
    op.drop_index(op.f('ix_batch_movements_nomenclature'), table_name='batch_movements')
    op.drop_index(op.f('ix_batch_movements_movement_date'), table_name='batch_movements')
    op.drop_index(op.f('ix_batch_movements_batch_number'), table_name='batch_movements')
    op.drop_table('batch_movements')
    op.drop_index(op.f('ix_batch_balances_nomenclature'), table_name='batch_balances')
    op.drop_index(op.f('ix_batch_balances_batch_number'), table_name='batch_balances')
    op.drop_index(op.f('ix_batch_balances_balance_date'), table_name='batch_balances')
    op.drop_table('batch_balances')
    # ### end Alembic commands ###
